import type { NextPage } from 'next'
import Head from 'next/head'
import ChartContainer from '../components/chart-container/chart-container'
import ChartCumAdmissionsByAge from '../components/chart-cum-admissions-by-age/chart-cum-admissions-by-age'
import ChartVaccinated from '../components/chart-vaccinated/chart-vaccinated'
import MainPanel from '../components/main-panel/main-panel'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

    return (
        <div className={styles.container}>
            <Head>
                <title>The data on coronavirus in the UK (COVID-19)</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className={styles.header}>
                <p className={styles.title} >The data on coronavirus in the UK (COVID-19)</p>
            </header>
            <main className={styles.main}>
                <div className={styles.page}>
                    <MainPanel />
                    <div className={styles.charts}>
                        <ChartContainer
                            title='New people vaccinated 1nd and 2nd dose in the last 30 days'
                            ChartElement={<ChartVaccinated />}
                        />
                        <ChartContainer
                            title='Total number of patients admitted to hospital with COVID-19 since the start of the pandemic, by age'
                            ChartElement={<ChartCumAdmissionsByAge />} />
                    </div>
                </div>
            </main>
        </div>
    )
}

export default Home
